# ============================================================
# DÉMO 1/3 — Secrets : utilisation de base
# ============================================================
# Un secret = une variable chiffrée, jamais visible dans
# les logs ni dans le code.
#
# Avant de tester ce workflow, créez un secret :
#   GitHub → votre dépôt → Settings
#   → Secrets and variables → Actions
#   → New repository secret
#   Nom   : MON_TOKEN
#   Valeur: une-valeur-de-test-quelconque
#
# Syntaxe : ${{ secrets.NOM_DU_SECRET }}
# ============================================================

name: "21 · Secrets — utilisation basique"

on: workflow_dispatch

jobs:
  demo-secret:
    name: "Utiliser un secret"
    runs-on: ubuntu-latest

    steps:
      - name: "🔐 Injecter le secret via env:"
        # ✅ BONNE PRATIQUE : injecter le secret dans env:
        # et l'utiliser comme variable shell ensuite.
        # Ne jamais mettre ${{ secrets.X }} directement dans run:
        env:
          MON_TOKEN: ${{ secrets.MON_TOKEN }}
        run: |
          echo "Le secret est injecté en variable d'environnement"
          echo "Longueur du token : ${#MON_TOKEN} caractères"
          echo "Premiers caractères : ${MON_TOKEN:0:3}***"

      - name: "👁️ GitHub masque automatiquement les secrets"
        env:
          MON_TOKEN: ${{ secrets.MON_TOKEN }}
        run: |
          echo "Même si on affiche la valeur, GitHub la masque :"
          echo "Valeur : $MON_TOKEN"
          # Dans les logs GitHub, la valeur apparaît comme : ***

      - name: "ℹ️ GITHUB_TOKEN — secret automatique"
        # GITHUB_TOKEN existe toujours, sans configuration
        run: |
          echo "GITHUB_TOKEN est automatiquement disponible"
          echo "Il permet d'interagir avec l'API GitHub"
          echo "Longueur : ${#GITHUB_TOKEN} caractères"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
