# ============================================================
# DÉMO 2/3 — Secrets : plusieurs secrets + vérification
# ============================================================
# Cas réel : un déploiement nécessite plusieurs secrets
# (identifiant + mot de passe + URL du serveur).
#
# Secrets à créer dans Settings → Secrets and variables :
#   DEPLOY_HOST     → adresse du serveur (ex: 192.168.1.1)
#   DEPLOY_USER     → utilisateur SSH (ex: ubuntu)
#   DEPLOY_SSH_KEY  → clé privée SSH (contenu du fichier)
#
# Ce workflow montre comment les utiliser et comment
# vérifier qu'ils ont bien été configurés.
# ============================================================

name: "22 · Secrets — plusieurs secrets + vérification"

on: workflow_dispatch

jobs:
  demo-multi-secrets:
    name: "Vérifier la présence des secrets"
    runs-on: ubuntu-latest

    steps:
      - name: "🔍 Vérifier que les secrets sont bien configurés"
        env:
          DEPLOY_HOST:    ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER:    ${{ secrets.DEPLOY_USER }}
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          echo "=== Vérification des secrets ==="

          # Un secret non configuré a une longueur de 0
          check_secret() {
            local name="$1"
            local value="$2"
            if [ -z "$value" ]; then
              echo "❌ $name : NON CONFIGURÉ"
            else
              echo "✅ $name : configuré (${#value} caractères)"
            fi
          }

          check_secret "DEPLOY_HOST"    "$DEPLOY_HOST"
          check_secret "DEPLOY_USER"    "$DEPLOY_USER"
          check_secret "DEPLOY_SSH_KEY" "$DEPLOY_SSH_KEY"

      - name: "🚀 Simuler un déploiement SSH"
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          if [ -z "$DEPLOY_HOST" ] || [ -z "$DEPLOY_USER" ]; then
            echo "⚠️  Secrets manquants — déploiement simulé seulement"
            echo "    Connexion SSH : $DEPLOY_USER@$DEPLOY_HOST"
          else
            echo "🚀 Connexion à $DEPLOY_USER@$DEPLOY_HOST..."
            echo "   (connexion SSH simulée pour la démo)"
          fi
